import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";
import Header from "@/components/Header";
import React from "react";
import Footer from "@/components/Footer";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import FontDocumentSync from "@/components/font/FontDocumentSync";
import DevtoolsEasterEgg from "@/components/DevtoolsEasterEgg";
import StructuredData from "./structured-data";
import { helveticaNeue, geist, instrumentSerif, jetbrainsMono } from "./fonts";
import { ThemeProvider } from "next-themes";
import ThemeFavicon from "@/components/theme/ThemeFavicon";
import { THEME_FAVICON_INIT_SCRIPT } from "@/lib/themeFaviconInitScript";

config.autoAddCss = false;

export const metadata: Metadata = {
  metadataBase: new URL("https://danielastudillo.io"),
  title: {
    default: "Daniel Astudillo — Software Engineer in New York",
    template: "%s | Daniel Astudillo",
  },
  description:
    "Daniel Astudillo is a software engineer in New York City building high-performance data platforms and full-stack systems at S&P Global. I write about performance, distributed systems, and shipping software that holds up in production.",
  keywords: [
    "Daniel Astudillo",
    "software engineer",
    "software engineer New York City",
    "performance engineering",
    "distributed systems",
    "full-stack engineer",
    "TypeScript",
    ".NET",
  ],
  authors: [{ name: "Daniel Astudillo", url: "https://danielastudillo.io" }],
  creator: "Daniel Astudillo",
  publisher: "Daniel Astudillo",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://danielastudillo.io",
    title: "Daniel Astudillo — Software Engineer in New York",
    description:
      "Software engineer in NYC building high-performance data platforms and full-stack systems. Writing about performance, distributed systems, and production engineering.",
    siteName: "Daniel Astudillo",
    // og:image is generated by app/opengraph-image.tsx (brand card).
  },
  twitter: {
    card: "summary_large_image",
    title: "Daniel Astudillo — Software Engineer in New York",
    description:
      "Software engineer in NYC building high-performance data platforms and full-stack systems.",
    // twitter:image falls back to the generated opengraph-image.
  },
  // Note: canonical URLs are set per-page, not in root layout
  // Each page should set its own canonical URL in its metadata
  // This prevents Google from treating all pages as redirects to the homepage
  alternates: {
    types: {
      "application/rss+xml": [
        { url: "/feed.xml", title: "Daniel Astudillo — Writing (RSS)" },
      ],
    },
  },
  verification: {
    google:
      "google-site-verification=meze9z3hYiB2JgJvuX2cIUCJGlj8oY3YlKIxDh23_g4", // Add your Google Search Console verification code
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning data-scroll-behavior="smooth">
      <head>
        {/* rel="me" for identity verification - helps with SEO and social linking */}
        <link rel="me" href="https://linkedin.com/in/daniel-m-astudillo" />
        <link rel="me" href="https://github.com/D-Astudillo-ASC" />
        <StructuredData />
        <style
          dangerouslySetInnerHTML={{
            __html: `
              /* Minimal critical CSS for above-the-fold layout */
              .flex { display: flex; }
              .flex-col { flex-direction: column; }
              .items-center { align-items: center; }
              .justify-center { justify-content: center; }
              .min-h-[80vh] { min-height: 80vh; }
              .px-4 { padding-left: 1rem; padding-right: 1rem; }
              .gap-4 { gap: 1rem; }
              .mb-4 { margin-bottom: 1rem; }
              .mb-8 { margin-bottom: 2rem; }
              .px-6 { padding-left: 1.5rem; padding-right: 1.5rem; }
              .py-2 { padding-top: 0.5rem; padding-bottom: 0.5rem; }
              .rounded { border-radius: 0.25rem; }
              .border { border-width: 1px; }
              .transition-colors { transition-property: color, background-color, border-color, text-decoration-color, fill, stroke; }
              .duration-200 { transition-duration: 200ms; }
              .cursor-pointer { cursor: pointer; }
            `,
          }}
        />
      </head>
      <body
        className={`${geist.variable} ${instrumentSerif.variable} ${jetbrainsMono.variable} ${helveticaNeue.variable}`}
        suppressHydrationWarning
      >
        <Script id="theme-favicon-init" strategy="beforeInteractive">
          {THEME_FAVICON_INIT_SCRIPT}
        </Script>
        <Script src="/scripts/font-init.js" strategy="beforeInteractive" />
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ThemeFavicon />
          <FontDocumentSync />
          <DevtoolsEasterEgg />
          <Header />
          <main className="flex flex-grow flex-col">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
