import Link from "next/link";
import { projects } from "@/data/projects";
import Introduction from "@/components/Introduction";
import type { Metadata } from "next";
import Hero from "@/components/Hero";
import FeaturedProjects from "@/components/FeaturedProjects";
import { getAllPosts } from "@/lib/posts";

// Force static generation for better performance
export const dynamic = "force-static";
export const revalidate = 3600;

const featuredProjects = projects
  .filter((project) => project.featured)
  .slice(0, 3);

export const metadata: Metadata = {
  title: { absolute: "Daniel Astudillo — Software Engineer in New York" },
  description:
    "Software engineer in New York City building high-performance data platforms and full-stack systems at S&P Global — previously payment infrastructure at Visa. I write about making software fast and reliable.",
  alternates: {
    canonical: "https://danielastudillo.io",
  },
  openGraph: {
    url: "https://danielastudillo.io",
    type: "website",
    title: "Daniel Astudillo — Software Engineer in New York",
    description:
      "Software engineer in NYC building high-performance data platforms and full-stack systems. Previously payment and eligibility APIs at Visa at production scale.",
    siteName: "Daniel Astudillo",
    locale: "en_US",
    // og:image generated by app/opengraph-image.tsx.
  },
  twitter: {
    card: "summary_large_image",
    title: "Daniel Astudillo — Software Engineer in New York",
    description:
      "Software engineer in NYC building high-performance data platforms and full-stack systems.",
  },
};

export default async function Home() {
  const recentPosts = (await getAllPosts()).slice(0, 3);

  return (
    <>
      {/* Hero — full viewport height */}
      <Hero />

      {/* Featured work */}
      <FeaturedProjects featuredProjects={featuredProjects} />

      {/* Writing — latest essays */}
      {recentPosts.length > 0 && (
        <section className="px-6 py-20 md:px-12 lg:px-24">
          <div className="mx-auto max-w-6xl">
            <div className="mb-10 flex items-baseline justify-between">
              <h2 className="font-mono text-xs tracking-[0.2em] uppercase text-muted">
                <span className="text-accent">02</span>
                <span className="px-2 text-muted/40">/</span>
                Writing
              </h2>
              <Link
                href="/blog"
                className="font-mono text-xs text-muted/60 hover:text-text transition-fast"
              >
                All writing →
              </Link>
            </div>
            <ul className="divide-y divide-border border-y border-border">
              {recentPosts.map((post) => (
                <li key={post.slug}>
                  <Link
                    href={`/blog/${post.slug}`}
                    className="group flex flex-col gap-2 py-6 transition-fast md:flex-row md:items-baseline md:justify-between md:gap-8"
                  >
                    <div className="max-w-2xl">
                      <h3 className="font-display text-2xl italic leading-snug text-text transition-fast group-hover:text-accent">
                        {post.title}
                      </h3>
                      <p className="mt-2 text-sm leading-relaxed text-muted">
                        {post.excerpt}
                      </p>
                    </div>
                    <p className="shrink-0 font-mono text-xs uppercase tracking-[0.18em] text-muted/70">
                      {new Date(post.date).toLocaleDateString("en-US", {
                        month: "short",
                        year: "numeric",
                      })}{" "}
                      · {post.readingTime}
                    </p>
                  </Link>
                </li>
              ))}
            </ul>
          </div>
        </section>
      )}

      {/* About snapshot — stats + short bio */}
      <section className="px-6 py-20 md:px-12 lg:px-24">
        <div className="mx-auto max-w-6xl">
          <div className="mb-10 flex items-baseline justify-between">
            <h2 className="font-mono text-xs tracking-[0.2em] uppercase text-muted">
              <span className="text-accent">03</span>
              <span className="px-2 text-muted/40">/</span>
              About
            </h2>
            <Link
              href="/about"
              className="font-mono text-xs text-muted/60 hover:text-text transition-fast"
            >
              Full story →
            </Link>
          </div>
          <div className="max-w-2xl">
            <Introduction />
          </div>
        </div>
      </section>
    </>
  );
}
