import type { Metadata } from "next";
import { getPostSlugs } from "@/lib/posts";

const SITE_URL = "https://danielastudillo.io";

export default async function Page({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const postModule = await import(`../content/${slug}/content.mdx`);
  const Post = postModule.default;
  const meta = postModule.metadata || {};
  const url = `${SITE_URL}/blog/${slug}`;

  const articleSchema = {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    headline: meta.title || "Blog Post",
    description: meta.description || meta.excerpt || "",
    image: meta.cover ? `${SITE_URL}${meta.cover}` : `${SITE_URL}/images/og-image.png`,
    datePublished: meta.date || new Date().toISOString(),
    dateModified: meta.dateModified || meta.date || new Date().toISOString(),
    keywords: Array.isArray(meta.tags) ? meta.tags.join(", ") : undefined,
    inLanguage: "en-US",
    author: { "@id": `${SITE_URL}/#person` },
    publisher: { "@id": `${SITE_URL}/#person` },
    isPartOf: { "@id": `${SITE_URL}/#website` },
    mainEntityOfPage: { "@type": "WebPage", "@id": url },
    url,
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }}
      />
      <Post />
    </>
  );
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const postModule = await import(`../content/${slug}/content.mdx`);
  const meta = postModule.metadata || {};
  const url = `${SITE_URL}/blog/${slug}`;
  const title = meta.title || "Writing";
  const description = meta.description || meta.excerpt || "An essay by Daniel Astudillo.";

  return {
    title,
    description,
    keywords: Array.isArray(meta.tags) ? meta.tags : undefined,
    alternates: { canonical: url },
    openGraph: {
      title,
      description,
      url,
      type: "article",
      publishedTime: meta.date,
      modifiedTime: meta.dateModified ?? meta.date,
      authors: ["Daniel Astudillo"],
      tags: meta.tags,
      siteName: "Daniel Astudillo",
      // og:image generated by app/blog/[slug]/opengraph-image.tsx (per-post card).
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
    },
  };
}

export function generateStaticParams() {
  return getPostSlugs().map((slug) => ({ slug }));
}

export const dynamicParams = false;
